### ISSUE TITLE
voce poderia fazer um plugin pro meu server de minecraft?

### ISSUE THREAD

**Issue by arthurmaia** [BrunoSilvaFreire/estudo-imoveis#1]
serve mainecrefiti pluguim venom extreme monark leon coisa de nerde

**Comment by BrunoSilvaFreire** [comment]
<img src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExYjUyNW1zcTJ4bW5xem85OXBtNjZrdHBhNXI5Ymg4aWRpdXc2emV5aiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/LAKIIRqtM1dqE/giphy.gif"/>
